site_name: Starling Egg
site_url: https://www.egg.tools/
site_description: Starling Egg is a Grasshopper template geared towards project collaboration.
site_author: Starling Associates
base_url: https://www.egg.tools/
repo_name: 'GitHub'
repo_url: https://github.com/starling-cloud/egg/
edit_uri_template: 'docs/{path}'

lang: en

dev_addr: 127.0.0.1:8888

theme:
  name: material
  custom_dir: 'docs/overrides'
  locale: en
  palette:
    scheme: starling
    # primary: 'teal'
    # accent: 'light'
  logo: assets/image/logo_light.png
  favicon: assets/favicon/favicon.ico
  features:
  #   - navigation.tabs
  #   - navigation.tabs.sticky
  #   - navigation.expand
  #   - navigation.indexes
  #   - toc.integrate
    - search.highlight
    - search.suggest

extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

extra:
  generator: false
  analytics:
    provider: google
    property: G-PECP1TMR9X
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.starling.associates
    - icon: fontawesome/brands/github 
      link: https://github.com/starling-cloud
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/starling-associates/
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/starling.cloud/
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/starlingclouds/

copyright: Copyright &copy; 2022 Starling Associates

# markdown_extensions:
#   - meta
#   - md_in_html
#   - toc:
#       permalink: true
#   - pymdownx.emoji:
#       emoji_index: !!python/name:materialx.emoji.twemoji
#       emoji_generator: !!python/name:materialx.emoji.to_svg

# hide:
#   - footer

nav:
  - Introduction: 'index.md'
  - Quick Start: 'quick_start.md'
  - Guide:
      - 'Introduction': 'guide/introduction.md'
      - 'Directory Structure': 'guide/directory_structure.md'
      - 'Layer Structure': 'guide/layer_structure.md'
      - 'Legend': 'guide/legend.md'
      - 'Colour Codes': 'guide/colour_codes.md'
  - Best Practices:
      - 'Introduction': 'best_practices/introduction.md'
      - 'Dependencies': 'best_practices/dependencies.md'
      - 'Sketches': 'best_practices/sketches.md'
      - 'Named Views': 'best_practices/named_views.md'
      - 'Geometry Pipeline': 'best_practices/geometry_pipeline.md'
      - 'Preview Mesh Edges': 'best_practices/preview_mesh_edges.md'
  - Resources:
      - 'Glossary': 'resources/glossary.md'
      - 'Plugins': 'resources/plugins.md'
      - 'Links': 'resources/links.md'
  - About:
      - 'Authors': 'about/authors.md'
      - 'Acknowledgements': 'about/acknowledgements.md'
  - Legal Information:
      - 'License': 'legal/license.md'
      - 'Privacy Policy': 'legal/privacy_policy.md'
      - 'Disclaimer': 'legal/disclaimer.md'
