site_name: Starling Egg
site_url: https://www.egg.tools/
site_description: Starling Egg is a Grasshopper template geared towards project collaboration.
site_author: Starling Associates
lang: en

repo_name: 'GitHub'
repo_url: https://github.com/starling-cloud/egg/
edit_uri_template: 'docs/{path}'

dev_addr: 127.0.0.1:8888

theme:
  name: material
  locale: en
  palette:
    scheme: starling
    # primary: light blue
  logo: assets/image/logo_light.png
  favicon: assets/favicon/favicon.ico
  # features:
  #   - navigation.tabs

extra_css:
  - assets/style/extra.css
extra_javascript:
  - assets/script/extra.js
extra_templates:

extra:
  generator: false
  # analytics:
  #   provider: google
  #   property: G-XXXXXXXXXX
  social:
    - icon: fontawesome/solid/globe 
      link: https://www.starling.associates
    - icon: fontawesome/brands/github 
      link: https://github.com/starling-cloud
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/starling-associates/
    - icon: fontawesome/brands/instagram 
      link: https://instagram.com/starling.cloud/
    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/starlingclouds/

copyright: Copyright &copy; 2022 Starling Associates

hide:
  - footer


nav:
  - Getting Started:
      - 'Introduction': 'index.md'
  - Guide:
      - 'Introduction': 'guide/introduction.md'
      - 'Colour Codes': 'guide/colour_codes.md'
  - Best Practices:
      - 'Introduction': 'best_practices/introduction.md'
      - 'Sketches': 'best_practices/sketches.md'
  - Glossary: 'glossary.md'
  - License: 'license.md'
  - Privacy Policy: 'privacy.md'